version: 2

updates:
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      docs:
        patterns:
          - "sphinx*"
      tests:
        patterns:
          - "freezegun"
          - "pytest*"
      linters:
        patterns:
          - "basedpyright"
          - "django-stubs"
          - "mypy"
          - "ruff"
          - "tox*"
          - "types-*"
          - "zizmor"
      django-devtools:
        patterns:
          - "django-debug-toolbar"
          - "django-extensions"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      actions:
        patterns:
          - "*"
