version: 2

build:
  image: latest

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

sphinx:
  builder: htmldir
  configuration: docs/conf.py

formats: all
