from collections.abc import Iterable
from typing import Any

from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpRequest, HttpResponse
from django.utils.feedgenerator import Enclosure, SyndicationFeed

class FeedDoesNotExist(ObjectDoesNotExist): ...

# Unlike the bundled django-types stub, this local override makes Feed
# generic over the item type and the object returned by get_object().
class Feed[ItemT, ObjectT]:
    feed_type: type[SyndicationFeed]
    title_template: str | None
    description_template: str | None
    language: str | None
    def __call__(
        self,
        request: HttpRequest,
        *args: Any,
        **kwargs: Any,
    ) -> HttpResponse: ...
    def get_object(
        self,
        request: HttpRequest,
        *args: Any,
        **kwargs: Any,
    ) -> ObjectT: ...
    def items(self, obj: ObjectT) -> Iterable[ItemT]: ...
    def item_title(self, item: ItemT) -> str: ...
    def item_description(self, item: ItemT) -> str: ...
    def item_link(self, item: ItemT) -> str: ...
    def item_enclosures(self, item: ItemT) -> list[Enclosure]: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_feed(self, obj: ObjectT, request: HttpRequest) -> SyndicationFeed: ...
    def feed_extra_kwargs(self, obj: ObjectT) -> dict[str, Any]: ...
    def item_extra_kwargs(self, item: ItemT) -> dict[str, Any]: ...
