# Generated by Django 6.0.7 on 2026-08-10 18:36

from django.db import migrations, models
from django.db.models import Count, Min


def remove_duplicate_subscriptions(apps, schema_editor):
    """Keep the oldest subscription of every user and comic, delete the rest."""
    Subscription = apps.get_model("accounts", "Subscription")
    duplicates = (
        Subscription.objects.values("userprofile", "comic")
        .annotate(count=Count("pk"), keep=Min("pk"))
        .filter(count__gt=1)
    )
    for duplicate in duplicates:
        Subscription.objects.filter(
            userprofile=duplicate["userprofile"],
            comic=duplicate["comic"],
        ).exclude(pk=duplicate["keep"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_id_as_bigautofield"),
        ("core", "0004_alter_image_file"),
    ]

    operations = [
        migrations.RunPython(
            remove_duplicate_subscriptions,
            migrations.RunPython.noop,
            elidable=True,
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("userprofile", "comic"), name="unique_subscription"
            ),
        ),
    ]
