#!/bin/sh
#
# SITE_NAME, DB_NAME and SET_TBL are assumed to be defined by the environment.
#

if [ "$1" = "config" ]; then
    echo graph_title "$SITE_NAME - Sets"
    echo graph_category comics
    echo graph_vlabel
    echo sets.label Sets
    exit 0
fi

SETS=`psql $DB_NAME -qt -c "SELECT COUNT(*) FROM $SET_TBL"`
echo sets.value $SETS
