#!/bin/sh
#
# SITE_NAME, DB_NAME, RELEASE_TBL, and IMAGE_TBL are assumed to be defined by
# the environment.
#

if [ "$1" = "config" ]; then
    echo graph_title "$SITE_NAME - Releases and images"
    echo graph_category comics
    echo graph_vlabel
    echo releases.label Releases
    echo images.label Images
    exit 0
fi

RELEASES=`psql $DB_NAME -qt -c "SELECT COUNT(*) FROM $RELEASE_TBL"`
IMAGES=`psql $DB_NAME -qt -c "SELECT COUNT(*) FROM $IMAGE_TBL"`
echo releases.value $RELEASES
echo images.value $IMAGES
