#!/bin/sh
#
# SITE_NAME, DB_NAME and COMIC_TBL are assumed to be defined by the
# environment.
#
if [ "$1" = "config" ]; then
	echo graph_title "$SITE_NAME - Number of comics"
	echo graph_category comics
	echo graph_vlabel
	echo comics.label Comics
	exit 0
fi
COMICS=`psql $DB_NAME -qt -c "SELECT COUNT(*) FROM $COMIC_TBL"`
echo comics.value $COMICS

