# Generated by Django 6.0.6 on 2026-07-18 16:52

from django.db import migrations, models

import comics.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_id_as_bigautofield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(
                height_field="height",
                upload_to=comics.core.models.image_file_path,
                width_field="width",
            ),
        ),
    ]
