name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Docs"
            python: "3.14"
            tox: docs
          - name: "pytest (3.12)"
            python: "3.12"
            tox: "3.12"
          - name: "pytest (3.13)"
            python: "3.13"
            tox: "3.13"
          - name: "pytest (3.14)"
            python: "3.14"
            tox: "3.14"
            coverage: true
          - name: "mypy"
            python: "3.14"
            tox: mypy
          - name: "ruff-format"
            python: "3.14"
            tox: ruff-format
          - name: "ruff-lint"
            python: "3.14"
            tox: ruff-lint
          - name: "zizmor"
            python: "3.14"
            tox: zizmor
    name: ${{ matrix.name }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          python-version: ${{ matrix.python }}
          activate-environment: true
      - run: uv pip install tox tox-uv
      - run: tox -e ${{ matrix.tox }}
        if: ${{ ! matrix.coverage }}
      - run: tox -e ${{ matrix.tox }} -- --cov-report=xml
        if: ${{ matrix.coverage }}
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        if: ${{ matrix.coverage }}
        with:
          use_oidc: true

  publish:
    name: "Publish image"
    needs: main
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=sha,format=long
      - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      - uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GIT_SHA=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
