name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "pytest (3.12)"
            python: "3.12"
            tox: "3.12"
          - name: "pytest (3.13)"
            python: "3.13"
            tox: "3.13"
          - name: "pytest (3.14)"
            python: "3.14"
            tox: "3.14"
            coverage: true
          - name: "ruff-format"
            python: "3.14"
            tox: ruff-format
          - name: "ruff-lint"
            python: "3.14"
            tox: ruff-lint
          - name: "mypy"
            python: "3.14"
            tox: mypy
          - name: "docs"
            python: "3.14"
            tox: docs

    name: ${{ matrix.name }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v6.0.3
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python }}
          activate-environment: true
      - run: uv pip install tox tox-uv
      - run: tox -e ${{ matrix.tox }}
        if: ${{ ! matrix.coverage }}
      - run: tox -e ${{ matrix.tox }} -- --cov-report=xml
        if: ${{ matrix.coverage }}
      - uses: codecov/codecov-action@v7
        if: ${{ matrix.coverage }}
        with:
          use_oidc: true
